spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:15432/quotes"
    username: postgres
    password: password
  jpa:
    open-in-view: false
  docker:
    compose:
      # details at https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.docker-compose.lifecycle
      lifecycle-management: start-and-stop
      start:
        command: up
      stop:
        command: down
        timeout: 1m
      file: basic-quotes-postgres-db/docker-compose.yml
