eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
    fetch-registry: true # We need to call other services so lets get fetch what's registered in eureka
    register-with-eureka: true # We don't offer services for others to call so lets not register in eureka

server:
  port: 0

