---
apiVersion: v1
kind: Namespace
metadata:
  name: basic-quotes-in-memory-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-boot
  namespace: basic-quotes-in-memory-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-quotes-in-memory-db
  template:
    metadata:
      labels:
        app: basic-quotes-in-memory-db
    spec:
      containers:
        - name: quotes
          image: basic-quotes-in-memory-db:1
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=80"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              # cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            periodSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]

---
apiVersion: v1
kind: Service
metadata:
  name: basic-quotes-in-memory-db
  namespace: basic-quotes-in-memory-db
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: basic-quotes-in-memory-db
  type: NodePort
