spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      eureka:
        client:
          registerWithEureka: false
          fetchRegistry: true
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/  # eureka server url
      discovery:
        locator:
          enabled: true  # enable the routes based on service discovery
      routes:
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/message-service/**
          filters:
            - StripPrefix=2
        - id: ui
          uri: http://localhost:5173
          predicates:
            - Path=/**

# expose all the spring boot actuators good for demos.
# NEVER DO THIS in production
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8080

