server:
  port: 8080
  shutdown: graceful # tell the server to wait for executing requests to finish before shutdown

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"